### ISSUE TITLE
The extension is not working anymore

### ISSUE THREAD

**Issue by aslampr07** [john-guo/simply-view-image-for-python-opencv-debugging#24] opened 2024-02-14 15:58 UTC
I am not seeing the yellow bulb anymore

   
![Screenshot_20240214_212754](https://github.com/john-guo/simply-view-image-for-python-opencv-debugging/assets/19869134/e1183cd5-45bd-46c2-8be6-a8bf2d4bc64e)

**Comment by john-guo** [comment] 2024-02-15 07:10
I have confirmed that the issue is caused by a change in the name of the Python debugger after a Visual Studio Code update. The problem has been resolved with the release of version 0.0.10, please update the extension to this new version. Thank you.

**Closed as completed by john-guo** 2024-02-15 07:10 UTC

**Comment by aslampr07** [comment] 2024-02-15 15:22
Thank you @john-guo for the quick resolution. The extension is really helpful for my workflow.
